application: elcerdoquerie
version: 1b
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/(.*\.png)
  static_files: static/\1
  upload: static/.*\.png

- url: /jobs/.*
  script: jobs.py
  login: admin

- url: /logos/[a-zA-Z0-9]+
  script: logos.py

- url: /.*
  script: index.py

